import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const targetDir = 'C:\\Users\\alarc\\Box\\All Files\\Budget-Tracker\\.obsidian\\plugins\\obsidian-budget-plugin';

const copyToVaultPlugin = {
	name: 'copy-to-vault',
	setup(build) {
		build.onEnd(async () => {
			const fs = (await import('fs')).promises;
			try {
				await fs.mkdir(targetDir, { recursive: true });
				await fs.copyFile('main.js', targetDir + '/main.js');
				await fs.copyFile('manifest.json', targetDir + '/manifest.json');
				try { await fs.copyFile('styles.css', targetDir + '/styles.css'); } catch (e) { }
				console.log(`✅ Auto-synced to Vault`);
			} catch (err) {
				console.error('Error copying files to vault:', err);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyToVaultPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
